export const data = {
	id: '200000004',
	tooltip: 'Thing',
	label: 'Node1',
	description: null,
	descriptionZh: null,
	depth: 3,
	subTypeCount: 9,
	status: 0,
	children: [
	  {
		id: '500000061',
		tooltip: 'Person',
		label: 'Node2',
		description: null,
		descriptionZh: null,
		depth: 1,
		subTypeCount: 1,
		status: 0,
		children: [
		  {
			id: '707000085',
			tooltip: 'FilmPerson',
			label: 'Node 2-1',
			description: null,
			descriptionZh: null,
			depth: 5,
			subTypeCount: 3,
			status: 1,
			children: [
			  {
				id: '707000090',
				tooltip: 'FilmDirector',
				label: 'Node 2-1-1',
				description: null,
				descriptionZh: null,
				depth: 0,
				subTypeCount: 0,
				status: 1,
				children: [],
			  },
			  {
				id: '707000091',
				tooltip: 'FilmWriter',
				label: 'Node 2-1-2',
				description: null,
				descriptionZh: null,
				depth: 4,
				subTypeCount: 0,
				status: 1,
				children: [],
			  },
			  {
				id: '707000092',
				tooltip: 'FilmStar',
				label: 'Node 2-1-3',
				description: null,
				descriptionZh: null,
				depth: 4,
				subTypeCount: 0,
				status: 1,
				children: [],
			  },
			],
		  },
		  {
			id: '707000086',
			tooltip: 'MusicPerson',
			label: 'Node 2-2',
			description: null,
			descriptionZh: null,
			depth: 17,
			subTypeCount: 2,
			status: 1,
			children: [],
		  },
		],
	  },
	  {
		id: '200000005',
		tooltip: 'Music',
		label: 'Node3',
		description: null,
		descriptionZh: null,
		depth: 3,
		subTypeCount: 2,
		status: 1,
		children: [],
	  },
	  {
		id: '707000128',
		tooltip: 'Film',
		label: 'Node4',
		description: null,
		descriptionZh: null,
		depth: 4,
		subTypeCount: 0,
		status: 1,
		children: [
		  {
			id: '7070032328',
			tooltip: 'Comedy',
			label: 'Node 4-1',
			description: null,
			descriptionZh: null,
			depth: 4,
			operation: 'C',
			subTypeCount: 0,
			status: 1,
			children: [],
		  },
		],
	  },
	  {
		id: '707000095',
		tooltip: 'FilmGenre',
		label: 'Node5',
		description: null,
		descriptionZh: null,
		depth: 4,
		subTypeCount: 0,
		status: 1,
		children: [],
	  },
	  {
		id: '702000021',
		tooltip: 'Organization',
		label: 'Node6',
		description: null,
		descriptionZh: null,
		depth: 47,
		  subTypeCount: 1,
		  color: 'red',
		status: 0,
		children: [
		  {
			id: '500000063',
			tooltip: 'Company',
			label: 'Node 6-1',
			description: null,
			descriptionZh: null,
			depth: 4,
			subTypeCount: 2,
			status: 1,
			children: [
			  {
				id: '707000093',
				tooltip: 'FilmCompany',
				label: 'Node 6-1-1',
				description: null,
				descriptionZh: null,
				depth: 4,
				subTypeCount: 0,
				status: 1,
				children: [],
			  },
			  {
				id: '707000094',
				tooltip: 'MusicCompany',
				label: 'Node 6-1-2',
				description: 'description 1234',
				descriptionZh: 'description',
				  depth: 2,
				  name: 'Ramiro',
				color: 'red',
				subTypeCount: 0,
				status: 1,
				children: [],
			  },
			],
		  },
		],
	  },
	],
  };